compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: ./deepspeed.json
  deepspeed_hostfile: ./hostfile
  deepspeed_multinode_launcher: pdsh
  zero3_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_config:
  dynamo_backend: INDUCTOR
machine_rank: 0
main_process_ip: 182.12.116.10
main_process_port: 22
main_training_function: main
num_machines: 2
num_processes: 16
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false